// <auto-generated>
//     This code was generated by a BlazorBindingsAvalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using AI = Avalonia.Interactivity;
using BlazorBindingsAvalonia.Elements;

#pragma warning disable CA2252

namespace BlazorBindingsAvalonia.Elements.Interactivity
{
    /// <summary>
    /// Base class for objects that raise routed events.
    /// </summary>
    public partial class Interactive : BlazorBindingsAvalonia.Elements.Layout.Layoutable
    {
        static Interactive()
        {
            RegisterAdditionalHandlers();
        }

        public new AI.Interactive NativeControl => (AI.Interactive)((AvaloniaObject)this).NativeControl;

        protected override AI.Interactive CreateNativeElement() => new();


        static partial void RegisterAdditionalHandlers();
    }
}
