// <auto-generated>
//     This code was generated by a BlazorBindingsAvalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using AL = Avalonia.Layout;
using BlazorBindingsAvalonia.Elements;

#pragma warning disable CA2252

namespace BlazorBindingsAvalonia.Elements.Layout
{
    /// <summary>
    /// Represents the base class for an object that sizes and arranges child elements for a host and supports virtualization.
    /// </summary>
    public abstract partial class VirtualizingLayout : AttachedLayout
    {
        static VirtualizingLayout()
        {
            RegisterAdditionalHandlers();
        }

        public new AL.VirtualizingLayout NativeControl => (AL.VirtualizingLayout)((AvaloniaObject)this).NativeControl;



        static partial void RegisterAdditionalHandlers();
    }
}
