// <auto-generated>
//     This code was generated by a BlazorBindingsAvalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using Microsoft.AspNetCore.Components;
using System.Threading.Tasks;
using System.Windows.Input;

#pragma warning disable CA2252

namespace BlazorBindingsAvalonia.Elements
{
    /// <summary>
    /// A standard button control.
    /// </summary>
    public partial class Button
    {   
    }
}
