// <auto-generated>
//     This code was generated by a BlazorBindingsAvalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>



#pragma warning disable CA2252

namespace BlazorBindingsAvalonia.Elements
{
    /// <summary>
    /// A control that displays a block of formatted text.
    /// </summary>
    public partial class SelectableTextBlock : TextBlock
    {
        static SelectableTextBlock()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the brush that highlights selected text.
        /// </summary>
        [Parameter] public global::Avalonia.Media.IBrush SelectionBrush { get; set; }
        /// <summary>
        /// Gets or sets a character index for the end of the current selection.
        /// </summary>
        [Parameter] public int? SelectionEnd { get; set; }
        /// <summary>
        /// Gets or sets a brush that is used for the foreground of selected text
        /// </summary>
        [Parameter] public global::Avalonia.Media.IBrush SelectionForegroundBrush { get; set; }
        /// <summary>
        /// Gets or sets a character index for the beginning of the current selection.
        /// </summary>
        [Parameter] public int? SelectionStart { get; set; }
        [Parameter] public EventCallback<global::Avalonia.Interactivity.RoutedEventArgs> OnCopyingToClipboard { get; set; }

        public new AC.SelectableTextBlock NativeControl => (AC.SelectableTextBlock)((AvaloniaObject)this).NativeControl;

        protected override AC.SelectableTextBlock CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(SelectionBrush):
                    if (!Equals(SelectionBrush, value))
                    {
                        SelectionBrush = (global::Avalonia.Media.IBrush)value;
                        NativeControl.SelectionBrush = SelectionBrush;
                    }
                    break;
                case nameof(SelectionEnd):
                    if (!Equals(SelectionEnd, value))
                    {
                        SelectionEnd = (int?)value;
                        NativeControl.SelectionEnd = SelectionEnd ?? (int)AC.SelectableTextBlock.SelectionEndProperty.GetDefaultValue(AC.SelectableTextBlock.SelectionEndProperty.OwnerType);
                    }
                    break;
                case nameof(SelectionForegroundBrush):
                    if (!Equals(SelectionForegroundBrush, value))
                    {
                        SelectionForegroundBrush = (global::Avalonia.Media.IBrush)value;
                        NativeControl.SelectionForegroundBrush = SelectionForegroundBrush;
                    }
                    break;
                case nameof(SelectionStart):
                    if (!Equals(SelectionStart, value))
                    {
                        SelectionStart = (int?)value;
                        NativeControl.SelectionStart = SelectionStart ?? (int)AC.SelectableTextBlock.SelectionStartProperty.GetDefaultValue(AC.SelectableTextBlock.SelectionStartProperty.OwnerType);
                    }
                    break;
                case nameof(OnCopyingToClipboard):
                    if (!Equals(OnCopyingToClipboard, value))
                    {
                        void NativeControlCopyingToClipboard(object sender, global::Avalonia.Interactivity.RoutedEventArgs e) => InvokeEventCallback(OnCopyingToClipboard, e);

                        OnCopyingToClipboard = (EventCallback<global::Avalonia.Interactivity.RoutedEventArgs>)value;
                        NativeControl.CopyingToClipboard -= NativeControlCopyingToClipboard;
                        NativeControl.CopyingToClipboard += NativeControlCopyingToClipboard;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
