// <auto-generated>
//     This code was generated by a BlazorBindingsAvalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>



#pragma warning disable CA2252

namespace BlazorBindingsAvalonia.Elements
{
    /// <summary>
    /// A separator control.
    /// </summary>
    public partial class Separator : BlazorBindingsAvalonia.Elements.Primitives.TemplatedControl
    {
        static Separator()
        {
            RegisterAdditionalHandlers();
        }

        public new AC.Separator NativeControl => (AC.Separator)((AvaloniaObject)this).NativeControl;

        protected override AC.Separator CreateNativeElement() => new();


        static partial void RegisterAdditionalHandlers();
    }
}
