// <auto-generated>
//     This code was generated by a BlazorBindingsAvalonia component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using ACP = Avalonia.Controls.Primitives;
using BlazorBindingsAvalonia.Elements;

#pragma warning disable CA2252

namespace BlazorBindingsAvalonia.Elements.Primitives
{
    public partial class TabStrip<T> : SelectingItemsControl<T>
    {
        static TabStrip()
        {
            RegisterAdditionalHandlers();
        }

        public new ACP.TabStrip NativeControl => (ACP.TabStrip)((AvaloniaObject)this).NativeControl;

        protected override ACP.TabStrip CreateNativeElement() => new();


        static partial void RegisterAdditionalHandlers();
    }
}
